const coins = [
    { value: "bitcoin", label: "Bitcoin" },
    { value: "ethereum", label: "Ethereum" },
    { value: "tether", label: "Tether" },
    { value: "binancecoin", label: "Binance Coin" },
    { value: "cardano", label: "Cardano" },
    { value: "ripple", label: "XRP" },
    { value: "dogecoin", label: "Dogecoin" },
    { value: "polkadot", label: "Polkadot" },
    { value: "litecoin", label: "Litecoin" },
    { value: "bitcoin-cash", label: "Bitcoin Cash" },
    { value: "chainlink", label: "Chainlink" },
    { value: "stellar", label: "Stellar" },
    { value: "usd-coin", label: "USD Coin" },
    { value: "uniswap", label: "Uniswap" },
    { value: "wrapped-bitcoin", label: "Wrapped Bitcoin" },
    { value: "binance-usd", label: "Binance USD" },
    { value: "eos", label: "EOS" },
    { value: "nem", label: "NEM" },
    { value: "cosmos", label: "Cosmos" },
    { value: "aave", label: "Aave" },
    { value: "vechain", label: "VeChain" },
    { value: "monero", label: "Monero" },
    { value: "avalanche", label: "Avalanche" },
    { value: "theta", label: "Theta" },
    { value: "tezos", label: "Tezos" },
    { value: "tron", label: "TRON" },
    { value: "huobi-token", label: "Huobi Token" },
    { value: "crypto-com-chain", label: "Crypto.com Coin" },
    { value: "iota", label: "IOTA" },
    { value: "ftx-token", label: "FTX Token" },
    { value: "lido-staked-ether", label: "Lido Staked Ether" },
    { value: "terra-luna", label: "Terra" },
    { value: "compound", label: "Compound" },
    { value: "solana", label: "Solana" },
    { value: "binance-gbp-stable-coin", label: "Binance GBP Stable Coin" },
    { value: "cdai", label: "cDAI" },
    { value: "neo", label: "NEO" },
    { value: "maker", label: "Maker" },
    { value: "ftx-token", label: "FTX Token" },
    { value: "dai", label: "Dai" },
    { value: "terrausd", label: "TerraUSD" },
    { value: "kusama", label: "Kusama" },
    { value: "compound-usd-coin", label: "Compound USD Coin" },
    { value: "algorand", label: "Algorand" },
    { value: "chiliz", label: "Chiliz" },
    { value: "filecoin", label: "Filecoin" },
    { value: "binance-btc-stable-coin", label: "Binance BTC Stable Coin" },
    { value: "compound-ether", label: "Compound Ether" },
    { value: "helium", label: "Helium" },
    { value: "dash", label: "Dash" },
    { value: "unus-sed-leo", label: "Unus Sed Leo" },
    { value: "theta-fuel", label: "Theta Fuel" },
    { value: "the-graph", label: "The Graph" },
    { value: "quant-network", label: "Quant Network" },
    { value: "decred", label: "Decred" },
    { value: "zcash", label: "Zcash" },
    { value: "elrond-egld", label: "Elrond" },
    { value: "harmony", label: "Harmony" },
    { value: "compound-governance-token", label: "Compound Governance Token" },
    { value: "basic-attention-token", label: "Basic Attention Token" },
    { value: "havven", label: "Havven" },
    { value: "stacks", label: "Stacks" },
    { value: "enjincoin", label: "Enjin Coin" },
    { value: "bitcoin-sv", label: "Bitcoin SV" },
    { value: "flow", label: "Flow" },
    { value: "ecomi", label: "ECOMI" },
    { value: "decentraland", label: "Decentraland" },
    { value: "siacoin", label: "Siacoin" },
    { value: "holotoken", label: "Holo" },
    { value: "trueusd", label: "TrueUSD" },
    { value: "ravencoin", label: "Ravencoin" },
    { value: "icon", label: "ICON" },
    { value: "omisego", label: "OMG Network" },
    { value: "perpetual-protocol", label: "Perpetual Protocol" },
    { value: "0x", label: "0x" },
    { value: "safemoon", label: "SafeMoon" },
    { value: "huobi-btc", label: "Huobi BTC" },
    { value: "iostoken", label: "IOST" },
    { value: "nexus", label: "Nexus" },
    { value: "verge", label: "Verge" },
    { value: "quant", label: "Quant" },
    { value: "fantom", label: "Fantom" },
    { value: "helium", label: "Helium" },
    { value: "zilliqa", label: "Zilliqa" },
    { value: "waves", label: "Waves" },
    { value: "qtum", label: "Qtum" },
    { value: "kusama", label: "Kusama" },
    { value: "zencash", label: "Horizen" },
    { value: "omg", label: "OMG Network" },
    { value: "bitcoin-gold", label: "Bitcoin Gold" },
    { value: "hedera-hashgraph", label: "Hedera Hashgraph" },
    { value: "siacoin", label: "Siacoin" },
    { value: "nano", label: "Nano" },
    { value: "digibyte", label: "DigiByte" },
    { value: "decentraland", label: "Decentraland" },
    { value: "zcash", label: "Zcash" },
    { value: "icon", label: "ICON" },
    { value: "omisego", label: "OMG Network" },
    { value: "theta-fuel", label: "Theta Fuel" },
    { value: "perpetual-protocol", label: "Perpetual Protocol" },
    { value: "0x", label: "0x" },
    { value: "safemoon", label: "SafeMoon" },
    { value: "huobi-btc", label: "Huobi BTC" },
    { value: "iostoken", label: "IOST" },
    { value: "nexus", label: "Nexus" },
    { value: "verge", label: "Verge" },
    { value: "quant", label: "Quant" },
    { value: "fantom", label: "Fantom" },
    { value: "helium", label: "Helium" },
    { value: "zilliqa", label: "Zilliqa" },
    { value: "waves", label: "Waves" },
    { value: "qtum", label: "Qtum" },
    { value: "kusama", label: "Kusama" },
    { value: "zencash", label: "Horizen" },
    { value: "omg", label: "OMG Network" },
    { value: "bitcoin-gold", label: "Bitcoin Gold" },
    { value: "hedera-hashgraph", label: "Hedera Hashgraph" },
    { value: "siacoin", label: "Siacoin" },
    { value: "nano", label: "Nano" },
    { value: "digibyte", label: "DigiByte" },
    { value: "decentraland", label: "Decentraland" },
    { value: "zcash", label: "Zcash" },
    { value: "icon", label: "ICON" },
    { value: "omisego", label: "OMG Network" },
    { value: "theta-fuel", label: "Theta Fuel" },
    { value: "perpetual-protocol", label: "Perpetual Protocol" },
    { value: "0x", label: "0x" },
    { value: "safemoon", label: "SafeMoon" },
    { value: "huobi-btc", label: "Huobi BTC" },
    { value: "iostoken", label: "IOST" },
    { value: "nexus", label: "Nexus" },
    { value: "verge", label: "Verge" },
    { value: "quant", label: "Quant" },
    { value: "fantom", label: "Fantom" },
    { value: "helium", label: "Helium" },
    { value: "zilliqa", label: "Zilliqa" },
    { value: "waves", label: "Waves" },
    { value: "qtum", label: "Qtum" },
    { value: "kusama", label: "Kusama" },
    { value: "zencash", label: "Horizen" },
    { value: "omg", label: "OMG Network" },
    { value: "bitcoin-gold", label: "Bitcoin Gold" },
    { value: "hedera-hashgraph", label: "Hedera Hashgraph" },
    { value: "siacoin", label: "Siacoin" },
    { value: "nano", label: "Nano" },
    { value: "digibyte", label: "DigiByte" },
    { value: "decentraland", label: "Decentraland" },
    { value: "zcash", label: "Zcash" },
    { value: "icon", label: "ICON" },
    { value: "omisego", label: "OMG Network" },
    { value: "theta-fuel", label: "Theta Fuel" },
    { value: "perpetual-protocol", label: "Perpetual Protocol" },
    { value: "0x", label: "0x" },
    { value: "safemoon", label: "SafeMoon" },
    { value: "huobi-btc", label: "Huobi BTC" },
    { value: "iostoken", label: "IOST" },
    { value: "nexus", label: "Nexus" },
    { value: "verge", label: "Verge" },
    { value: "quant", label: "Quant" },
    { value: "fantom", label: "Fantom" },
    { value: "helium", label: "Helium" },
    { value: "zilliqa", label: "Zilliqa" },
    { value: "waves", label: "Waves" },
    { value: "qtum", label: "Qtum" },
    { value: "kusama", label: "Kusama" },
    { value: "zencash", label: "Horizen" },
    { value: "omg", label: "OMG Network" },
    { value: "bitcoin-gold", label: "Bitcoin Gold" },
    { value: "hedera-hashgraph", label: "Hedera Hashgraph" },
    { value: "siacoin", label: "Siacoin" },
    { value: "nano", label: "Nano" },
    { value: "digibyte", label: "DigiByte" },
  ];
 
  export default coins;
 

